@extends('layouts.app')
@section('title',__('Program Certificates'))
@section('header')<h2 style="margin:0;font-size:1.15rem;font-weight:800;">{{ __('Program Certificates') }}</h2>@endsection
@section('content')
<main style="max-width:1400px;margin:0 auto;padding:1.5rem;display:grid;gap:1rem;">
 <section class="card" style="padding:1.5rem;"><div style="display:flex;align-items:flex-start;justify-content:space-between;gap:1rem;"><div><h1 style="margin:0 0 .35rem;">{{ __('Certificate Search') }}</h1><p style="color:var(--text-muted);">{{ __('Find a certificate using matric number, student name, certificate serial number, or program.') }}</p></div><a class="btn" href="{{ !empty($filters['program_id']) ? route('admin.programs.operations', $filters['program_id']) : route('admin.programs.index') }}">{{ !empty($filters['program_id']) ? __('Back to Program Operations') : __('Back to Program Management') }}</a></div>
 <form method="get" style="display:grid;grid-template-columns:minmax(260px,1fr) 220px 240px auto;gap:.7rem;margin-top:1rem;"><input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="{{ __('Matric number, name or serial number') }}"><select name="program_id"><option value="">{{ __('All programs') }}</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected(($filters['program_id']??null)==$program->id)>{{ $program->title }}</option>@endforeach</select><select name="status"><option value="">{{ __('All statuses') }}</option>@foreach(['pending','generating','ready','failed'] as $status)<option value="{{ $status }}" @selected(($filters['status']??'')===$status)>{{ __(ucfirst($status)) }}</option>@endforeach</select><button class="btn btn-primary">{{ __('Search') }}</button></form></section>
 <section style="display:grid;grid-template-columns:repeat(4,1fr);gap:.8rem;">@foreach(['pending','generating','ready','failed'] as $status)<article class="card" style="padding:1rem;"><small>{{ __(strtoupper($status)) }}</small><strong style="display:block;font-size:1.6rem;margin-top:.25rem;">{{ number_format($stats[$status]??0) }}</strong></article>@endforeach</section>
 <section class="card" style="padding:0;overflow:hidden;"><div style="overflow:auto;"><table style="width:100%;border-collapse:collapse;"><thead><tr><th>{{ __('Student') }}</th><th>{{ __('Matric Number') }}</th><th>{{ __('Program') }}</th><th>{{ __('Certificate') }}</th><th>{{ __('Status') }}</th><th>{{ __('Action') }}</th></tr></thead><tbody>@forelse($certificates as $certificate)<tr><td>{{ $certificate->student_name }}</td><td><strong>{{ $certificate->matric_no }}</strong></td><td>{{ $certificate->program_title }}</td><td>{{ $certificate->serial_no }}</td><td><span class="badge">{{ __(ucfirst($certificate->status)) }}</span></td><td>@if($certificate->status==='ready')<a class="btn" href="{{ route('admin.program-certificates.download',$certificate->id) }}">{{ __('Download') }}</a>@else—@endif</td></tr>@empty<tr><td colspan="6" style="padding:2rem;text-align:center;">{{ __('No certificate records found.') }}</td></tr>@endforelse</tbody></table></div></section>
 {{ $certificates->links() }}
</main>
@endsection
